# Generated by Django 4.0.8 on 2022-10-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_day_day_mesocycle_mesocycle_week_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='mesocycle',
            name='mesocycle',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
