# Generated by Django 4.0.8 on 2022-10-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_day_day_alter_mesocycle_mesocycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout.exercise'),
        ),
    ]
